[versions]
agp = "8.5.0"
kotlin = "1.9.0"
coreKtx = "1.13.1"
leanback = "1.0.0"
glide = "4.11.0"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-leanback = { group = "androidx.leanback", name = "leanback", version.ref = "leanback" }
glide = { group = "com.github.bumptech.glide", name = "glide", version.ref = "glide" }
navigation = { group = "androidx.navigation", name = "navigation-fragment-ktx", version = "2.7.7" }
[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

